spring:
  application:
    name: naocs-example
  cloud:
   nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          management.context-path: /foo
          health.path: /ping
          user.name: admin
          user.password: admin
  profiles:
    active:
      - secure
management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: /ping
      base-path: /foo
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8084
---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "admin"

