spring:
  application:
    name: consul-example
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: management.context-path=/foo, health.path=/ping, user.name=admin, user.password=admin
  profiles:
    active:
      - secure
  boot:
    admin:
      discovery:
        ignored-services: consul


management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: /ping
      base-path: /foo
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "admin"

